hugo-build:
  image: registry.gitlab.com/pages/hugo:latest
  stage: build

  variables:
    GIT_SUBMODULE_STRATEGY: recursive

  script:
    - hugo version
    - hugo
  artifacts:
    paths:
      - public
  only:
    variables:
      - $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

hugo-deploy:
  image: ubuntu
  stage: deploy
  before_script:
    - "which ssh-agent || ( apt-get update -y && apt-get install openssh-client git -y )"
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan tylinux.com >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts

  script:
    - tar zcvf public.tar.gz public/
    - scp public.tar.gz tylinux@tylinux.com:docker/nginx
    - ssh tylinux@tylinux.com "cd docker/nginx; tar zxvf public.tar.gz; rm public.tar.gz; cd ~/docker; docker-compose restart nginx"
