stages:
  - build
  - deploy
  - sync
  - notification

hugo-build:
  image: registry.tylinux.com/hugo:latest
  stage: build

  variables:
    GIT_SUBMODULE_STRATEGY: recursive

  script:
    - hugo version
    - hugo
  artifacts:
    paths:
      - public
  only:
    variables:
      - $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

hugo-deploy:
  image: registry.tylinux.com/gitlab-ssh:latest
  stage: deploy

  script:
    - bash /setup.sh
    - tar zcvf public.tar.gz public/
    - scp public.tar.gz tylinux@tylinux.com:docker/nginx
    - ssh tylinux@tylinux.com "cd docker/nginx; tar zxvf public.tar.gz; rm public.tar.gz; cd ~/docker; docker-compose restart nginx"

push-github:
  image: registry.tylinux.com/gitlab-ssh:latest
  stage: sync

  script:
    - bash /setup.sh
    - git remote add upstream git@github.com:tylinux/blog.git
    - git push upstream master

notification:
  image: registry.tylinux.com/send_tg:latest
  stage: notification
  script:
    - send_tg $TG_PRIVATE_ID -t "博客部署成功!"
