baseURL = "https://www.tylinux.com/"
languageCode = "zh_CN"
title = "不正经的正经程序猿"
theme = "maupassant"
preserveTaxonomyNames = true
disablePathToLower = true


[author]
  name = "tylinux"

[params]
  author = "tylinux"
  subtitle = "一个人的命运啊，当然要靠自我奋斗，但是也要考虑历史的行程"
  keywords = "iOS,macOS,逆向,Reverse,RE,越狱,jailbreak,xnure"
  description = "正经iOS/Linux程序员, 二进制安全新手, 越狱爱好者, 硬件 DIYer"
  busuanzi = true

[menu]
  [[menu.main]]
    identifier = "archives"
    name = "归档"
    url = "/archives/"
    weight = 2

  [[menu.main]]
    identifier = "about"
    name = "关于"
    url = "/about/"
    weight = 3

[params.cc]
    name = "知识共享署名-非商业性使用-禁止演绎 4.0 国际许可协议"
    link = "https://creativecommons.org/licenses/by-nc-nd/4.0/"

[params.utteranc]
    enable = true
    repo = "tylinux/BlogComments"
    issueTerm = "pathname"  #表示你选择以那种方式让github issue的评论和你的文章关联。
    theme = "github-light" # 样式主题，有github-light和github-dark两种
